[package]
name = "state-core"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "1.5.7"
hex = "0.4.3"
sdk = { workspace = true, features = ["smt"] }
sha2 = "0.10.8"
sparse-merkle-tree = { version = "0.6.1", default-features = false }
