global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: hyliquid-server
    metrics_path: /metrics
    static_configs:
      - targets:
          - host.docker.internal:9002
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: hyliquid-server

  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
