version: "2"

services:
  db:
    image: postgres
    ports:
      - "5433:5432"
    volumes:
      - /var/lib/postgresql/data
    # DB Version: 18
    # OS Type: linux
    # DB Type: oltp
    # Total Memory (RAM): 16 GB
    # CPUs num: 22
    # Connections num: 50
    # Data Storage: ssd

    command: >
      postgres
      -c shared_preload_libraries=pg_stat_statements
      -c pg_stat_statements.track=all
      -c max_connections=50
      -c shared_buffers=4GB
      -c effective_cache_size=12GB
      -c maintenance_work_mem=1GB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c default_statistics_target=100
      -c random_page_cost=1.1
      -c effective_io_concurrency=200
      -c work_mem=58254kB
      -c huge_pages=off
      -c min_wal_size=2GB
      -c max_wal_size=8GB
      -c max_worker_processes=22
      -c max_parallel_workers_per_gather=4
      -c max_parallel_workers=22
      -c max_parallel_maintenance_workers=4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
