id = "orderbook"
log_format = "full"

data_directory = "data"
da_read_from = "127.0.0.1:4141"

rest_server_port = 9002
rest_server_max_body_size = 10_485_760 # 10 MB
node_url = "http://localhost:4321"
indexer_url = "http://localhost:4322"

database_url = "postgresql://postgres:postgres@localhost:32777"
database_name = "hyliquid"

buffer_blocks = 0
max_txs_per_proof = 30
tx_working_window_size = 150

trigger_url = "http://localhost:3000/api/websocket/trigger"

[websocket]
port = 8082
ws_path = "/ws"
health_path = "/ws_health"
peer_check_interval.secs = 0
peer_check_interval.nanos = 100_000_000

# Sepolia testnet
[bridge]
eth_contract_vault_address = "0x2ffCC85Db88Dbb4047d4d1528CE7739CFB961302"
eth_contract_address = "0x22CE25BFa5Dcd58A3B52c2A5fa262bDF079A5456"
eth_contract_deploy_block = 9550540
eth_rpc_ws_url = "wss://eth-sepolia.g.alchemy.com/v2/aQBmpGJwCJZnOMUnvsLlC"
eth_rpc_http_url = "https://eth-sepolia.g.alchemy.com/v2/aQBmpGJwCJZnOMUnvsLlC"
eth_signer_private_key = "0x02caa170f44fa6218889783833f519818ade0a57b7878b9971f0cf9f3bb781dd"
