id = "orderbook"
log_format = "full"

data_directory = "data"
da_read_from = "127.0.0.1:4141"

rest_server_port = 9002
rest_server_max_body_size = 10_485_760                                              # 10 MB
node_url = "http://localhost:4321"
indexer_url = "http://localhost:4321"
indexer_database_url = "postgresql://postgres:postgres@localhost:5432/hyli_indexer"

database_url = "postgresql://postgres:postgres@localhost:5432"
database_name = "orderbook"

buffer_blocks = 0
max_txs_per_proof = 30
tx_working_window_size = 150
secret = [1, 2, 3]

trigger_url = "http://localhost:3000/api/websocket/trigger"

[websocket]
port = 8082
ws_path = "/ws"
health_path = "/ws_health"
peer_check_interval.secs = 0
peer_check_interval.nanos = 100_000_000

# Sepolia testnet
[bridge]
eth_contract_vault_address = "0x2ffCC85Db88Dbb4047d4d1528CE7739CFB961302"
eth_contract_address = "0x22CE25BFa5Dcd58A3B52c2A5fa262bDF079A5456"
eth_rpc_ws_url = "wss://0xrpc.io/sep"
eth_rpc_http_url = "https://0xrpc.io/sep"
eth_signer_private_key = ""
