id = "orderbook"
log_format = "full"

data_directory = "data"
da_read_from = "127.0.0.1:4141"

rest_server_port = 9002
rest_server_max_body_size = 10_485_760 # 10 MB
node_url = "http://localhost:4321"
indexer_url = "http://localhost:4321"

database_url = "postgresql://postgres:postgres@localhost:5432"
database_name = "orderbook"

buffer_blocks = 0
max_txs_per_proof = 30
tx_working_window_size = 150

trigger_url = "http://localhost:3000/api/websocket/trigger"

[websocket]
port = 8082
ws_path = "/ws"
health_path = "/ws_health"
peer_check_interval.secs = 0
peer_check_interval.nanos = 100_000_000


#LOCAL with anvil
[bridge]
eth_contract_vault_address = "0x15d34AAf54267DB7D7c367839AAf71A00a2C6A65"
eth_contract_address = "0x5FbDB2315678afecb367f032d93F642f64180aa3"
eth_contract_deploy_block = 0
eth_rpc_ws_url = "ws://localhost:8545"
eth_rpc_http_url = "http://localhost:8545"
eth_signer_private_key = "0x47e179ec197488593b187f80a00eb0da91f1b9d0b13f8733639f19c30a34926a"

# Sepolia testnet
# [bridge]
# eth_contract_vault_address = "0x2ffCC85Db88Dbb4047d4d1528CE7739CFB961302"
# eth_contract_address = "0x3fCC2158ECc22b318BCaB1FFc6E27A8e2d059C2F"
# eth_contract_deploy_block = 9305013
# eth_rpc_ws_url = "wss://eth-sepolia.g.alchemy.com/v2/aQBmpGJwCJZnOMUnvsLlC"
# eth_rpc_http_url = "https://eth-sepolia.g.alchemy.com/v2/aQBmpGJwCJZnOMUnvsLlC"
# eth_signer_private_key = "0x02caa170f44fa6218889783833f519818ade0a57b7878b9971f0cf9f3bb781dd"
