[package]
name = "state-example"
version = "0.1.0"
edition = "2021"

[dependencies]
state-core = { path = "../../macros/state-core" }
state-macros = { path = "../../macros/state-macros" }
borsh = "1.5.7"
sha2 = "0.10.8"
sparse-merkle-tree = { version = "0.6.1", default-features = false }
