name: Push to Artifact Registry

on:
  push:
    branches:
      - "releases/**"
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      build_server:
        description: "Build server image"
        type: boolean
        default: true
      build_ui:
        description: "Build ui image"
        type: boolean
        default: true
      build_api:
        description: "Build api image"
        type: boolean
        default: true

env:
  IMAGE_NAME: "hyliquid"
  PROJECT_ID: "hyle-413414"
  AR_REPO_LOCATION: "europe-west3"
  AR_URL: "europe-west3-docker.pkg.dev/hyle-413414/hyle-docker"
  SERVICE_ACCOUNT: "github-actions-service-account@hyle-413414.iam.gserviceaccount.com"
  WORKLOAD_IDENTITY_PROVIDER: ""

jobs:
  build_and_push:
    permissions:
      contents: "read"
      id-token: "write"
      packages: "write"

    runs-on: ubuntu-latest
    strategy:
      matrix:
        suffix:
          - server
          - ui
          - api

    steps:
      - name: Checkout
        if: |
          github.event_name == 'push' ||
          (matrix.suffix == 'server' && inputs.build_server) ||
          (matrix.suffix == 'ui' && inputs.build_ui) ||
          (matrix.suffix == 'api' && inputs.build_api)
        uses: actions/checkout@v2

      - name: Docker meta
        if: |
          github.event_name == 'push' ||
          (matrix.suffix == 'server' && inputs.build_server) ||
          (matrix.suffix == 'ui' && inputs.build_ui) ||
          (matrix.suffix == 'api' && inputs.build_api)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.AR_URL }}/${{ env.IMAGE_NAME }}-${{ matrix.suffix }}
            ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME }}-${{ matrix.suffix }}
          tags: |
            type=sha
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Docker Auth (Google Artifact Registry)
        if: |
          github.event_name == 'push' ||
          (matrix.suffix == 'server' && inputs.build_server) ||
          (matrix.suffix == 'ui' && inputs.build_ui) ||
          (matrix.suffix == 'api' && inputs.build_api)
        id: docker-auth
        uses: "docker/login-action@v3"
        with:
          username: _json_key
          password: ${{ secrets.GOOGLE_CREDENTIALS }}
          registry: "${{ env.AR_REPO_LOCATION }}-docker.pkg.dev"

      - name: Login to GitHub Container Registry
        if: |
          github.event_name == 'push' ||
          (matrix.suffix == 'server' && inputs.build_server) ||
          (matrix.suffix == 'ui' && inputs.build_ui) ||
          (matrix.suffix == 'api' && inputs.build_api)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        if: |
          github.event_name == 'push' ||
          (matrix.suffix == 'server' && inputs.build_server) ||
          (matrix.suffix == 'ui' && inputs.build_ui) ||
          (matrix.suffix == 'api' && inputs.build_api)
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          build-args: |
            DEP_IMAGE=europe-west3-docker.pkg.dev/hyle-413414/hyli-docker/hyli-dependencies:main
          file: Dockerfile.${{ matrix.suffix }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
